apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-docker-consumer
  template:
    metadata:
      labels:
        app: spring-docker-consumer
    spec:
      containers:
        - name: spring-docker-consumer
          image: yuriyweiss/spring-docker-consumer:0.0.6
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Moscow
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "150Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
