apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-docker-producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-docker-producer
  template:
    metadata:
      labels:
        app: spring-docker-producer
    spec:
      containers:
        - name: spring-docker-producer
          image: yuriyweiss/spring-docker-producer:{{CURRENT_VERSION}}
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Moscow
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "200Mi"
            limits:
              memory: "300Mi"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
